// part2/react-course/src/Course.jsx
import Header from './Header'
import Content from './Content'
import Total from './Total'

const Course = ({ course }) => {
    return (
        <>
            <Header course={course.name} />
            <Content parts={course.parts} />
            <Total parts={course.parts} />
        </>
    )
}

export default Course

// part2/svelte-course/src/routes/Course.svelte
<script>
    import Content from "./Content.svelte";
    import Header from "./Header.svelte";
    import Total from "./Total.svelte";

    let { courses } = $props()
</script>

<div>
    {#each courses as course (course.id)}
        <Header course = { course.name } />
        <Content parts = { course.parts } />
        <Total parts = { course.parts } />
    {/each}
</div>
