// part2/svelte-phonebook/src/routes/PersonForm.svelte
<script>
    let {persons} = $props()

    function onsubmit(e) {
        e.preventDefault()
        let newName = e.target.elements.name.value
        let newNumber = e.target.elements.number.value

        if(persons.find(p => p.name.toLowerCase() == newName.toLowerCase())){
            alert(`${newName} already present in phonebook!`)
            return
        }

        persons.push({name: newName, number: newNumber})

        e.target.elements.name.value = ""
        e.target.elements.number.value = ""
    }
</script>

<form {onsubmit}>
    <label>name:  <input name="name" /></label>
    <label>phone: <input name="number"/></label>
    <div><button type="submit">add</button></div>
</form>

<style>
    form {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        gap: 1rem;
    }
</style>

// part2/react-phonebook/src/PersonForm.jsx
const PersonForm = ({newName, setNewName, newNumber, setNewNumber, persons, setPersons}) => {
    function onSubmit(event){
      event.preventDefault()

      if(persons.find(p => p.name.toLowerCase() === newName.toLowerCase())){
        alert(`${newName} is already present in the phonebook!`)
        return
      }

      const newPerson = {name: newName, number: newNumber}
      setPersons(persons.concat(newPerson))
      setNewName("")
      setNewNumber("")

      console.log("debug: Form submitted!")
    }

    return (
        <form onSubmit={onSubmit}>
          <label>name:  <input value={newName} onChange={ e => setNewName(e.target.value)}/></label>
          <label>phone: <input value={newNumber} onChange={e => setNewNumber(e.target.value)}/></label>
          <div><button type="submit">add</button></div>
        </form>
    )
}

export default PersonForm
