// part3/svelte-phonebook/frontend/src/lib/components/Person.svelte
<script>
    import PersonService from "$lib/personService";

    let { persons, person, notification } = $props()

    async function onclick() {
        if(window.confirm(`Delete "${person.name}"?`)) {
            try {
                const response = await PersonService.remove(person.id)
                if(!response.ok) {
                    throw new Error("404", {cause: response})
                }
                const deletedPersonIndex = persons.findIndex(p => p.id === person.id)
                persons.splice(deletedPersonIndex, 1)
                notification.message = "Entry successfully deleted!"
                notification.error = false
            } catch (err) {
                console.error(`Error: ${err}`)
                notification.message = `${person.name} was already removed!`
                notification.error = true
            }
        }
    }
</script>

<div class="person">
    <p><span style="text-decoration: underline">{person.name}</span>: {person.number}</p>
    <div><button {onclick}>Delete</button></div>
</div>

<style>
    .person {
        display:flex;
        justify-content:space-between;
        align-items: center;
        gap: 1em;
        margin: 1em 0;
    }

    .person button {
        padding: 0.6em 1.2em;
        color: white;
        background-color: black;
    }
</style>

// part3/react-phonebook/frontend/src/components/Person.jsx
import PersonService from "../services/personService"

const Person = ({person, setMessage, setError }) => {

    async function onClick(){
        if(window.confirm(`Delete "${person.name}"?`)) {
            try {
                await PersonService.remove(person.id)
                // window.location.reload() // to allow re-fetching data from backend
                setMessage("Entry successfully deleted!")
                setError(false)
            } catch(error){
                console.error(`Error: ${error}`)
                setMessage(`"${person.name}" was already removed`)
                setError(true)
            }
        }
            
    }

    return (
        <div className="person">
            <p><span style={{textDecoration: 'underline'}}>{person.name}</span>: {person.number}</p> 
            <div><button onClick={onClick}>delete</button></div>
        </div>
    )
}

export default Person
