// part2/react-phonebook/src/components/PersonForm.jsx
import PersonService from '../services/personService'

const PersonForm = ({newName, setNewName, newNumber, setNewNumber, persons, setPersons, setMessage, setError}) => {
    async function onSubmit(event){
      event.preventDefault()

      let matchedPerson = persons.find(p => p.name.toLowerCase() === newName.toLowerCase())

      if(matchedPerson){
        if(!window.confirm(`${newName} is already present in the phonebook. \nUpdate phone number?`))
          return
        else {
          await PersonService.update(matchedPerson.id, {...matchedPerson, number: newNumber})
          setMessage("Entry successfully updated!")
          setError(false)
          return
        }
      }

      const newPerson = {name: newName, number: newNumber}

      const response = await PersonService.create(newPerson)

      setPersons(persons.concat(response.data))
      setNewName("")
      setNewNumber("")
      setMessage("Entry successfully added!")
      setError(false)

      console.log("debug: Form submitted!")
    }

    return (
        <form onSubmit={onSubmit}>
          <label>name:  <input value={newName} onChange={ e => setNewName(e.target.value)}/></label>
          <label>phone: <input value={newNumber} onChange={e => setNewNumber(e.target.value)}/></label>
          <div><button type="submit">add</button></div>
        </form>
    )
}

export default PersonForm

// part3/svelte-phonebook/frontend/src/lib/components/PersonForm.svelte
<script>
    import PersonService from "$lib/personService";

    let {persons, notification} = $props()

    async function onsubmit(e) {
        e.preventDefault()
        let newName = e.target.elements.name.value
        let newNumber = e.target.elements.number.value

        const matchedPerson = persons.find(p => p.name.toLowerCase() == newName.toLowerCase())

        if(matchedPerson){
            if(!window.confirm(`${newName} is already present in the phonebook. \nUpdate phone number?`))
                return
            else {
                await PersonService.update(matchedPerson.id, {...matchedPerson, number: newNumber})
                notification.message = "Entry successfully updated"
                notification.error = false
                
                // unable to find how to reload data w/o reloading page, so am just manually update persons rune instead
                const updatedPersonIndex = persons.findIndex(p => p.id === matchedPerson.id)
                persons[updatedPersonIndex] = {...matchedPerson, number: newNumber}

                e.target.elements.name.value = ""
                e.target.elements.number.value = ""
                return
            }
        }

        const newPerson = {name: newName, number: newNumber}
        const response = await PersonService.create(newPerson)
        const data = await response.json()

        notification.message = "Entry successfully added!"
        notification.error = false
        persons.push(data)

        e.target.elements.name.value = ""
        e.target.elements.number.value = ""
    }
</script>

<form {onsubmit}>
    <label>name:  <input name="name" /></label>
    <label>phone: <input name="number"/></label>
    <div><button type="submit">add</button></div>
</form>

<style>
    form {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        gap: 1rem;
    }
</style>
